-- MySQL Script generated by MySQL Workbench
-- Mon Jun 14 11:30:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mycard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mycard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycard` DEFAULT CHARACTER SET latin1 ;
USE `mycard` ;

-- -----------------------------------------------------
-- Table `mycard`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`account` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `activation_date` DATE NOT NULL,
  `passw` VARCHAR(32) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`users` (
  `user_id` INT(11) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `birth` DATE NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `photo` VARCHAR(300) NULL DEFAULT 'uploads/def.jpg',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC),
  INDEX `newUser` (`user_id` ASC),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`account` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`education_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`education_experience` (
  `education_experience_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `year` INT(11) NOT NULL,
  `place` VARCHAR(20) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`education_experience_id`),
  UNIQUE INDEX `education_experience_id` (`education_experience_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `education_experience_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`company` (
  `company_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `place` VARCHAR(40) NOT NULL,
  `web` VARCHAR(40) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `note` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `company_id` (`company_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`work_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`work_experience` (
  `work_experience_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `year` INT(11) NOT NULL,
  `place` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`work_experience_id`),
  UNIQUE INDEX `work_experience_id` (`work_experience_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `company_idx` (`company_id` ASC),
  CONSTRAINT `work_experience_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`users` (`user_id`),
  CONSTRAINT `work_experience_ibfk_2`
    FOREIGN KEY (`company_id`)
    REFERENCES `mycard`.`company` (`company_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`cards` (
  `card_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `photo` VARCHAR(300) NULL DEFAULT 'uploads/def.jpg',
  `note` VARCHAR(300) NULL DEFAULT NULL,
  `education_experience_id` INT(11) NOT NULL,
  `work_experience_id` INT(11) NOT NULL,
  PRIMARY KEY (`card_id`),
  UNIQUE INDEX `card_id` (`card_id` ASC),
  INDEX `education_experience_idx` (`education_experience_id` ASC),
  INDEX `work_experience_idx` (`work_experience_id` ASC),
  INDEX `newCARD` (`user_id` ASC),
  CONSTRAINT `cards_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`users` (`user_id`),
  CONSTRAINT `cards_ibfk_2`
    FOREIGN KEY (`education_experience_id`)
    REFERENCES `mycard`.`education_experience` (`education_experience_id`),
  CONSTRAINT `cards_ibfk_3`
    FOREIGN KEY (`work_experience_id`)
    REFERENCES `mycard`.`work_experience` (`work_experience_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`meeting` (
  `meeting_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `title` VARCHAR(40) NOT NULL,
  `place` VARCHAR(100) NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `topic` VARCHAR(300) NULL DEFAULT NULL,
  `lat` FLOAT(10,6) NOT NULL,
  `lng` FLOAT(10,6) NOT NULL,
  PRIMARY KEY (`meeting_id`),
  UNIQUE INDEX `meeting_id` (`meeting_id` ASC),
  INDEX `newMEETING` (`user_id` ASC),
  CONSTRAINT `meeting_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`invite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`invite` (
  `user_id` INT(11) NOT NULL,
  `meeting_id` INT(11) NOT NULL,
  `reply` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`, `meeting_id`),
  INDEX `newID` (`user_id` ASC),
  INDEX `newINVITE` (`meeting_id` ASC),
  CONSTRAINT `invite_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`users` (`user_id`),
  CONSTRAINT `invite_ibfk_2`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `mycard`.`meeting` (`meeting_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`partecipate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`partecipate` (
  `user_id` INT(11) NOT NULL,
  `meeting_id` INT(11) NOT NULL,
  `card_id` INT(11) NULL DEFAULT NULL,
  `note` VARCHAR(400) NULL DEFAULT NULL,
  `usefull` INT(11) NULL DEFAULT NULL,
  `importance` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `meeting_id`),
  INDEX `new_ID` (`user_id` ASC),
  INDEX `newPARTECIPATE` (`meeting_id` ASC),
  INDEX `card_idx` (`card_id` ASC),
  CONSTRAINT `partecipate_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`users` (`user_id`),
  CONSTRAINT `partecipate_ibfk_2`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `mycard`.`meeting` (`meeting_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `partecipate_ibfk_3`
    FOREIGN KEY (`card_id`)
    REFERENCES `mycard`.`cards` (`card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mycard`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycard`.`wallet` (
  `user_id` INT(11) NOT NULL,
  `meeting_id` INT(11) NOT NULL,
  `card_id` INT(11) NOT NULL,
  `note` VARCHAR(300) NULL DEFAULT NULL,
  `professionality` INT(11) NULL DEFAULT NULL,
  `impression` INT(11) NULL DEFAULT NULL,
  `aviability` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `meeting_id`, `card_id`),
  INDEX `new_USER` (`user_id` ASC),
  INDEX `new_MEETING` (`meeting_id` ASC),
  INDEX `newWALLET` (`card_id` ASC),
  CONSTRAINT `wallet_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mycard`.`users` (`user_id`),
  CONSTRAINT `wallet_ibfk_2`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `mycard`.`meeting` (`meeting_id`),
  CONSTRAINT `wallet_ibfk_3`
    FOREIGN KEY (`card_id`)
    REFERENCES `mycard`.`cards` (`card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
